import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {MAX_BODY,normalizeHeaders,parseBody,signHmac,safeTarget,toCurl,eventSummary} from './core.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const pub=path.join(__dirname,'../public');const events=[];const PORT=Number(process.env.PORT||8080);const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))};
async function read(req){return await new Promise((resolve,reject)=>{let size=0,chunks=[];req.on('data',c=>{size+=c.length;if(size>MAX_BODY){reject(new Error('Body exceeds 1 MB'));req.destroy();return}chunks.push(c)});req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}
async function handler(req,res){const u=new URL(req.url,'http://local'); if(u.pathname.startsWith('/hook/')){try{const raw=await read(req);const headers=normalizeHeaders(req.headers);const body=parseBody(raw,headers['content-type']||'');const e={id:crypto.randomUUID(),method:req.method,path:u.pathname+u.search,headers,query:Object.fromEntries(u.searchParams),body:body.value,bodyText:body.text,createdAt:new Date().toISOString()};events.unshift(e);events.splice(100);return json(res,202,{received:true,id:e.id})}catch(e){return json(res,413,{error:e.message})}}
if(u.pathname==='/api/events'&&req.method==='GET') return json(res,200,events.map(eventSummary));
if(u.pathname.startsWith('/api/events/')&&req.method==='GET'){const e=events.find(x=>x.id===u.pathname.split('/')[3]);return e?json(res,200,{...e,curl:toCurl(e)}):json(res,404,{error:'Event not found'})}
if(u.pathname==='/api/sign'&&req.method==='POST'){try{const d=JSON.parse((await read(req)).toString());return json(res,200,{signature:signHmac(d.secret,d.payload??'',d.algorithm||'sha256')})}catch(e){return json(res,400,{error:e.message})}}
if(u.pathname.startsWith('/api/replay/')&&req.method==='POST'){try{const e=events.find(x=>x.id===u.pathname.split('/')[3]);if(!e)return json(res,404,{error:'Event not found'});const d=JSON.parse((await read(req)).toString());const target=safeTarget(d.target);const r=await fetch(target,{method:e.method,headers:{'content-type':e.headers['content-type']||'application/octet-stream'},body:['GET','HEAD'].includes(e.method)?undefined:e.bodyText,redirect:'error',signal:AbortSignal.timeout(5000)});return json(res,200,{status:r.status,ok:r.ok})}catch(e){return json(res,400,{error:e.message})}}
if(u.pathname==='/api/export'&&req.method==='GET'){res.writeHead(200,{'content-type':'application/json','content-disposition':'attachment; filename="webhook-events.json"'});return res.end(JSON.stringify(events,null,2))}
let file=u.pathname==='/'?'index.html':u.pathname.slice(1);const full=path.join(pub,file);if(!full.startsWith(pub)||!fs.existsSync(full))return json(res,404,{error:'Not found'});const ext=path.extname(full);res.writeHead(200,{'content-type':ext==='.css'?'text/css':ext==='.js'?'text/javascript':'text/html'});fs.createReadStream(full).pipe(res)}
if(process.env.NODE_ENV!=='test')http.createServer(handler).listen(PORT,()=>console.log(`Webhook Playground: http://localhost:${PORT}`));export {handler};
